[general]
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/run/current-system/sw/bin/fish"

[font]
normal = { family = "JetbrainsMono Nerd Font" }
size = 11

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.98
blur = true

[selection]
save_to_clipboard = true

[terminal]
